export const ROUTES = [
  {
    id: 1,
    text: "Features",
    isActive: false,
    changeFrequency: "yearly",
    priority: 0.8,
    route: "/features",
  },
  // { id: 2, text: "Integrations", isActive: false, route: "/integrations" },
  {
    id: 2,
    text: "About",
    isActive: false,
    changeFrequency: "yearly",
    priority: 0.7,
    route: "/about-us",
  },
  {
    id: 3,
    text: "Contact Us",
    isActive: false,
    changeFrequency: "yearly",
    priority: 0.7,
    route: "/contact-us",
  },
  {
    id: 4,
    text: "Pricing",
    isActive: false,
    changeFrequency: "yearly",
    priority: 0.5,
    route: "/pricing",
  },
  // { id: 4, text: "Live Demo", isActive: false, route: "asd" },
  {
    id: 5,
    text: "Blog",
    isActive: false,
    changeFrequency: "yearly",
    priority: 0.5,
    route: "/blog",
  },
];
