import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Navigator from "@/components/templates/Navigator";
import Footer from "../(components)/Footer";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import { DEFAULT_METADATA } from "@/shared/constants/metadata.constant";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata({ params }) {
  // const locale = params.locale;
  // const messages = await getMessages();
  return DEFAULT_METADATA;
}

export default async function LocaleLayout({ children, params }) {
  const locale = (await params).locale;
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${poppins.className} antialiased overflow-x-hidden`}>
        <NextIntlClientProvider messages={messages}>
          <Navigator />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
